#!/bin/sh

set -eu

echo "Setting up dotfiles..."

ln -sf $PWD/oli.vimrc $HOME/.vimrc
ln -sf $PWD/tmux.conf $HOME/.tmux.conf
ln -sf $PWD/aliases $HOME/.aliases
ln -sf $PWD/bash.rc $HOME/.bashrc
ln -sf $PWD/init.nvim $HOME/.config/init.nvim


mkdir -p $HOME/.config/{bspwm,sxhkd,polybar}

ln -sf $PWD/.config/bspwm/bspwmrc $HOME/.config/bspwm/bspwmrc
ln -sf $PWD/.config/sxhkd/sxhkdrc $HOME/.config/sxhkd/sxhkdrc
ln -sf $PWD/.config/polybar/config $HOME/.config/polybar/config

echo "Done!"
